name: CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and package the library
        run: |
          yarn
          yarn build
          yarn package
